name = "sunny-and-ranney"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./dist"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "product-catalog"

[[d1_databases]]
binding = "DB"
database_name = "sunnyandranney-db"
database_id = "a3fbfba9-569c-4dae-af1a-4a1f290963f7"
